


# Class:
# Server


# Request:
#
# - Method
# - Path
# - Body

# Route
# 

# CGI
# - Path

server: 
  name: 3
  port: 80
  host: 127.0.0.1
  bodyLimit: 256
  route:
    path:
    dir: ./Html_code/
    default: 500.html
    methods:    GET  DELETE PUT
    listDir: false
    allowUpload: false
  route:
    path: hello
    dir: ./Html_code/
    default: file.html
    methods: GET
  route:
    path: hello2
    dir: ./Html_code/
    default: file.html
    methods:



    