


# Class:
# Server


# Request:
#
# - Method
# - Path
# - Body

# Route
# 

# CGI
# - Path
# defaultError: ./Html_code/418.html

# redir path cannot be empty unlike path. Use a slash to denote an empty path

server: 
  name: 3
  host: 127.0.0.1
  port: 8080
  bodyLimit: 40000000
  defaultError: ./Html_code/400.html
  route:
    path:
    dir: ./Html_code
    default: cgi.html
    methods:    GET  DELETE POST
    listDir: false
    uploadPath: ./upload
    redirPath: asdf
  route:
    path: asdf
    dir: ./Html_code
    methods:    GET  DELETE POST
    listDir: true
    allowUpload: true
    uploadPath: ./upload
    CGIs: .py .out
  route:
    path: asdf/haha
    dir: ./Html_code
    default: cgi.html
    methods:    GET  DELETE POST
    listDir: true
    allowUpload: true
    uploadPath: ./upload
    CGIs: .py .out
  route:
    path: hello
    dir: ./Html_code/
    default: delete.html
    methods: GET POST DELETE
    allowUpload: true
    uploadPath: ./upload
  route:
    path: hello2
    dir: ./Html_code
    default: file.html
    methods: GET POST DELETE
    CGIs: .py

server: 
  name: 3
  port: 8080
  host: 10.11.13.4
  bodyLimit: 256
  defaultError: 418.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false

server: 
  name: 3
  port: 8080
  host: localhost
  bodyLimit: 256
  defaultError: 418.html
  404: ./Html_code/400.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false


server: 
  name: 3
  port: 8080
  host: localhost
  bodyLimit: 256
  defaultError: ./Html_code/418.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false

  server:
    name: 4
    port: 80
    host: 127.0.0.1
    bodyLimit: 400
    defaultError: ./Html_code/400.html
    route:
      path:
      dir: ./Html_code/
      default: 418.html
    route:
      path: hello
      dir: ./Html_code/
      default: main.html
      methods: GET
      listDir: true
      allowUpload: false