


# Class:
# Server


# Request:
#
# - Method
# - Path
# - Body

# Route
# 

# CGI
# - Path

server: 
  name: 3
  port: 8080
  host: 127.0.0.1
  bodyLimit: 256
  defaultError: 418.html
  route:
    path:
    dir: ./Html_code
    default: file.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: true
    uploadPath: ./upload
  route:
    path: hello
    dir: ./Html_code/
    default: file.html
    methods: GET POST DELETE
  route:
    path: hello2
    dir: ./Html_code
    default: file.html
    methods:

server: 
  name: 3
  port: 8080
  host: 127.0.0.1
  bodyLimit: 256
  defaultError: 418.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false

server: 
  name: 3
  port: 8080
  host: localhost
  bodyLimit: 256
  defaultError: 418.html
  404: ./Html_code/400.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false


server: 
  name: 3
  port: 8080
  host: 10.11.14.3
  bodyLimit: 256
  defaultError: ./Html_code/418.html
  route:
    path: other
    dir: ./Html_code/
    default: 418.html
    methods:    GET  DELETE POST
    listDir: false
    allowUpload: false