


# Class:
# Server


# Request:
#
# - Method
# - Path
# - Body

# Route
# 

# CGI
# - Path

server: 
  name: 3
  port: 7070
  host: 345
  bodyLimit: 256
  route:
    path:
    dir:
    default:
    methods:
    listDir:
    redirPath:
    allowUpload:
    uploadPath:
    CGIs:



    